## DSS 615 - Fall 2021 Assignments
## Assignment-4B
Modified: 9/10/2021

Submit entire notebook as one file. Note there are several exercises in this assignment. **Remember to add your last name to the file name.**

Student Name: **CHANGE THIS TO YOUR NAME**

# Intro to Data Science: Transforming COVID-19 Data with Pandas

The purpose of this assignment is to transform the existing data file to a new format. 

You will: 
* Determine the 10 states or territories with the most cases or deaths in the US, YTD.
* Filter the data frame to include only those 10 states and territories and the columns date, state, positive, and death.
* Complete various data frame operations
* Create a simple bar chart show the top ten states

Note: more details in the cells below. Read them carefully

**LOOK at all output in notebook before restarting and clearing output. This will help you know what you are trying to create.**

# Retrieving daily COVID-19 data with `pandas`

Source: https://covidtracking.com

daily.csv
* cases are cummulative
* summarized daily by state
* we don't need all columns, just cummulative pos/neg test, date, state
* entire data dictionary at https://covidtracking.com/about-data/data-definitions

In [19]:
# need now
import pandas as pd
from datetime import datetime

# need later
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [20]:
# get data and put into pandas data frame
url = 'https://covidtracking.com/api/v1/states/daily.csv'

# create a pandas data frame from the csv file stored on internet
#       (do not use a local file since professor won't have access to it)

# vvv Your code below vvv
df = pd.read_csv(url)
# ^^^ Your code above ^^^

In [21]:
df.head()

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20210307,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,0,0,dc4bccd4bb885349d7e94d6fed058e285d4be164,0,0,0,0,0,NaN
1,20210307,AL,499819.0,107742.0,1931711.0,NaN,totalTestsPeopleViral,2323788.0,494.0,45976.0,...,NaN,-1,0,997207b430824ea40b8eb8506c19a93e07bc972e,0,0,0,0,0,NaN
2,20210307,AR,324818.0,69092.0,2480716.0,NaN,totalTestsViral,2736442.0,335.0,14926.0,...,NaN,22,11,50921aeefba3e30d31623aa495b47fb2ecc72fae,0,0,0,0,0,NaN
3,20210307,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,NaN,0,0,f77912d0b80d579fbb6202fa1a90554fc4dc1443,0,0,0,0,0,NaN
4,20210307,AZ,826454.0,56519.0,3073010.0,NaN,totalTestsViral,7908105.0,963.0,57907.0,...,NaN,5,44,0437a7a96f4471666f775e63e86923eb5cbd8cdf,0,0,0,0,0,NaN

In [22]:
df.tail()

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
20775,20200117,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,7cefac6b3681020741ca30f45399a7b22f2e45b4,0,0,0,0,0,NaN
20776,20200116,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,650501e005a5ee86d93c5f32dda56735ea2af967,0,0,0,0,0,NaN
20777,20200115,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,4987e61aad88182abfe641033b597304c2153d4f,0,0,0,0,0,NaN
20778,20200114,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,1881c8a2f0d337b22066b4f05df06eb2259e8d57,0,0,0,0,0,NaN
20779,20200113,WA,NaN,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,12b994ad07c276a5278a2465e081751688739765,0,0,0,0,0,NaN

In [23]:
## NO NEW CODE IN THIS CELL

# convert date from integer yyyymmdd to date format
df['date'] = pd.to_datetime(df['date'], format='%Y%m%d').dt.strftime("%Y-%m-%d")

# convert non-missing postitive and negative from float to int

df.death = df.death.fillna(0.0).astype(int) 
 
df  # not required but let's us see transformation

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,2021-03-07,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,0,0,dc4bccd4bb885349d7e94d6fed058e285d4be164,0,0,0,0,0,NaN
1,2021-03-07,AL,499819.0,107742.0,1931711.0,NaN,totalTestsPeopleViral,2323788.0,494.0,45976.0,...,NaN,-1,0,997207b430824ea40b8eb8506c19a93e07bc972e,0,0,0,0,0,NaN
2,2021-03-07,AR,324818.0,69092.0,2480716.0,NaN,totalTestsViral,2736442.0,335.0,14926.0,...,NaN,22,11,50921aeefba3e30d31623aa495b47fb2ecc72fae,0,0,0,0,0,NaN
3,2021-03-07,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,NaN,0,0,f77912d0b80d579fbb6202fa1a90554fc4dc1443,0,0,0,0,0,NaN
4,2021-03-07,AZ,826454.0,56519.0,3073010.0,NaN,totalTestsViral,7908105.0,963.0,57907.0,...,NaN,5,44,0437a7a96f4471666f775e63e86923eb5cbd8cdf,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20775,2020-01-17,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,7cefac6b3681020741ca30f45399a7b22f2e45b4,0,0,0,0,0,NaN
20776,2020-01-16,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,650501e005a5ee86d93c5f32dda56735ea2af967,0,0,0,0,0,NaN
20777,2020-01-15,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,4987e61aad88182abfe641033b597304c2153d4f,0,0,0,0,0,NaN
20778,2020-01-14,WA,0.0,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,1881c8a2f0d337b22066b4f05df06eb2259e8d57,0,0,0,0,0,NaN
20779,2020-01-13,WA,NaN,NaN,NaN,NaN,totalTestEncountersViral,NaN,NaN,NaN,...,NaN,0,0,12b994ad07c276a5278a2465e081751688739765,0,0,0,0,0,NaN

## Determine States with Most Deaths
* Create a new dataframe of just the states with the top cumulative deaths
* Create a list of the top ten state names
* Add a rank column to the new dataframe
* Create a bar chart

In [30]:
# Step 1: Filter dataframe to just the most current data  (or max date or max date - 1)
#       Do not assign to an object. View the output to confirm most recent data

# vvv Your code below vvv
df = df[df['date']=='2021-03-07']
df
# ^^^ Your code above ^^^

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,2021-03-07,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,0,0,dc4bccd4bb885349d7e94d6fed058e285d4be164,0,0,0,0,0,NaN
1,2021-03-07,AL,499819.0,107742.0,1931711.0,NaN,totalTestsPeopleViral,2323788.0,494.0,45976.0,...,NaN,-1,0,997207b430824ea40b8eb8506c19a93e07bc972e,0,0,0,0,0,NaN
2,2021-03-07,AR,324818.0,69092.0,2480716.0,NaN,totalTestsViral,2736442.0,335.0,14926.0,...,NaN,22,11,50921aeefba3e30d31623aa495b47fb2ecc72fae,0,0,0,0,0,NaN
3,2021-03-07,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,NaN,0,0,f77912d0b80d579fbb6202fa1a90554fc4dc1443,0,0,0,0,0,NaN
4,2021-03-07,AZ,826454.0,56519.0,3073010.0,NaN,totalTestsViral,7908105.0,963.0,57907.0,...,NaN,5,44,0437a7a96f4471666f775e63e86923eb5cbd8cdf,0,0,0,0,0,NaN
5,2021-03-07,CA,3501394.0,NaN,NaN,NaN,totalTestsViral,49646014.0,4291.0,NaN,...,NaN,258,0,63c5c0fd2daef2fb65150e9db486de98ed3f7b72,0,0,0,0,0,NaN
6,2021-03-07,CO,436602.0,24786.0,2199458.0,NaN,totalTestEncountersViral,6415123.0,326.0,23904.0,...,NaN,3,18,444746cda3a596f183f3fa3269c8cab68704e819,0,0,0,0,0,NaN
7,2021-03-07,CT,285330.0,19621.0,NaN,NaN,totalTestsViral,6520366.0,428.0,NaN,...,NaN,0,0,38f39494134d22cd0d06e4ce63aa4a4ac10aa930,0,0,0,0,0,NaN
8,2021-03-07,DC,41419.0,NaN,NaN,NaN,totalTestEncountersViral,1261363.0,150.0,NaN,...,NaN,0,0,a3aa0d623d538807fb9577ad64354f48cf728cc8,0,0,0,0,0,NaN
9,2021-03-07,DE,88354.0,4733.0,545070.0,NaN,totalTestEncountersViral,1431942.0,104.0,NaN,...,NaN,9,0,059d870e689d5cc19c35f5eb398214d7d9856373,0,0,0,0,0,NaN
10,2021-03-07,FL,1909209.0,360372.0,9339038.0,8544.0,totalTestEncountersViral,22339182.0,3307.0,82237.0,...,NaN,66,92,e69aca367d15584f4db13bd791804be1b017efc7,0,0,0,0,0,NaN
11,2021-03-07,GA,1023487.0,195151.0,NaN,NaN,totalTestsViral,7359069.0,2008.0,56797.0,...,NaN,1,35,d64d091b3e0b4c47cb7a80c60b7fc6dd1d15d6dd,0,0,0,0,0,NaN
12,2021-03-07,GU,7749.0,209.0,112887.0,NaN,posNeg,120636.0,2.0,NaN,...,NaN,0,0,b6fe9a2c36aa6e5b1f0b14dd057d23c6968b10a4,0,0,0,0,0,NaN
13,2021-03-07,HI,28699.0,808.0,NaN,NaN,totalTestEncountersViral,1146796.0,27.0,2226.0,...,NaN,1,0,4f2c09f953483ffc35e24ac50e0c6c1f10077002,0,0,0,0,0,NaN
14,2021-03-07,IA,282384.0,NaN,1044418.0,NaN,posNeg,1326802.0,167.0,NaN,...,NaN,6,0,33548da1aa99383ebd1ef74769d8bb1eba36b959,0,0,0,0,0,NaN
15,2021-03-07,ID,172931.0,33057.0,505964.0,NaN,totalTestsPeopleViral,645838.0,150.0,7184.0,...,NaN,3,5,78595a6705d321c83cba079dbee71b6db1897502,0,0,0,0,0,NaN
16,2021-03-07,IL,1198335.0,NaN,NaN,NaN,totalTestsViral,18640190.0,1141.0,NaN,...,NaN,12,0,b7f807d015574eb38516d454d35cc6c09effb16b,0,0,0,0,0,NaN
17,2021-03-07,IN,667262.0,NaN,2483156.0,NaN,totalTestsViral,8242367.0,656.0,43217.0,...,NaN,11,64,dcdfec9f776fcb6e79033397905f447c5fc756bc,0,0,0,0,0,NaN
18,2021-03-07,KS,295861.0,NaN,974686.0,NaN,posNeg,1270547.0,235.0,9387.0,...,NaN,0,0,71bcb3a00a03aa1b0c50376fdc9f22e1e9b5156b,0,0,0,0,0,NaN
19,2021-03-07,KY,410709.0,96324.0,NaN,NaN,totalTestsViral,3975672.0,558.0,19457.0,...,NaN,13,6,e75efcdb394b4f605892102108def98f76e402d4,0,0,0,0,0,NaN
20,2021-03-07,LA,433785.0,61271.0,5261679.0,NaN,posNeg,5695464.0,532.0,NaN,...,NaN,32,0,7fd45e084947a390edc7e73d1d9039015369dc7f,0,0,0,0,0,NaN
21,2021-03-07,MA,591356.0,32273.0,4404792.0,NaN,totalTestsViral,16825551.0,665.0,19713.0,...,NaN,43,0,acd1b6abdcc5a944bacbaa1f8fe621fc84c7e08e,0,0,0,0,0,NaN
22,2021-03-07,MD,387319.0,NaN,3034546.0,NaN,totalTestsViral,8097590.0,818.0,35651.0,...,NaN,14,79,f0e2e509e56cd4e825ca3673d540a4c6329c9a0c,0,0,0,0,0,NaN
23,2021-03-07,ME,45794.0,9948.0,NaN,NaN,totalTestsViral,1660180.0,67.0,1570.0,...,NaN,2,4,2375b3e026543e57fb7a7a75172d0a909b1483a3,0,0,0,0,0,NaN
24,2021-03-07,MI,656072.0,60018.0,NaN,NaN,totalTestsViral,10621967.0,866.0,NaN,...,NaN,0,0,0319b95a7e00d41ec841fc29e39b238055dc542d,0,0,0,0,0,NaN
25,2021-03-07,MN,490011.0,24464.0,3058514.0,NaN,totalTestEncountersViral,7111428.0,224.0,25978.0,...,NaN,4,2,28cbe3a55cc006f13f3a5397cc795403cf55d246,0,0,0,0,0,NaN
26,2021-03-07,MO,480643.0,NaN,1878583.0,NaN,totalTestsViral,4565866.0,955.0,NaN,...,NaN,0,0,69bb8a73e3a654573e0d38b349d6a92c7750b42d,0,0,0,0,0,NaN
27,2021-03-07,MP,145.0,NaN,17429.0,NaN,posNeg,17574.0,NaN,4.0,...,NaN,0,0,604ee9ce4dee663fe99123a19a712d867f8a0406,0,0,0,0,0,NaN
28,2021-03-07,MS,297581.0,113303.0,1459374.0,NaN,posNeg,1756955.0,419.0,9162.0,...,NaN,3,0,38d600ef762a2cde624501169ffae710e94913fe,0,0,0,0,0,NaN
29,2021-03-07,MT,100914.0,5524.0,NaN,NaN,totalTestsViral,1104488.0,63.0,4630.0,...,NaN,0,1,7643a815c17357244db67932096ff56f623be3aa,0,0,0,0,0,NaN
30,2021-03-07,NC,872176.0,112559.0,NaN,NaN,totalTestsViral,9688838.0,1179.0,NaN,...,NaN,0,0,d9ca67dd72ba6f8a8506ebb734fd25b0b8067608,0,0,0,0,0,NaN
31,2021-03-07,ND,100391.0,5463.0,305912.0,NaN,totalTestEncountersViral,1425146.0,23.0,3880.0,...,NaN,0,2,ee1d9ce00226b7456452f7d4f6674248577e0c4b,0,0,0,0,0,NaN
32,2021-03-07,NE,203026.0,NaN,771128.0,NaN,totalTestsViral,2421684.0,137.0,6237.0,...,NaN,0,8,3f55dc5e02818a3abbd58e07cf80bdfe4abc60f1,0,0,0,0,0,NaN
33,2021-03-07,NH,76861.0,22797.0,579582.0,NaN,totalTestsViral,1497185.0,68.0,1131.0,...,NaN,3,4,984a5b49a111e92bec03e2188180fa977e211111,0,0,0,0,0,NaN
34,2021-03-07,NJ,812609.0,91670.0,10186941.0,NaN,posNeg,10999550.0,1792.0,64396.0,...,NaN,17,58,343068629601e5564b578db7541484baf3ef552f,0,0,0,0,0,NaN
35,2021-03-07,NM,186922.0,NaN,NaN,NaN,totalTestsViral,2783542.0,169.0,13252.0,...,NaN,12,10,254a01ca85894315ed1ae612eb1b457ed198ac62,0,0,0,0,0,NaN
36,2021-03-07,NV,296190.0,NaN,1131758.0,NaN,totalTestEncountersViral,2770192.0,399.0,NaN,...,NaN,1,0,fcbdfd6c3ee8359e623bb9bc5a6bdb0fc780b75e,0,0,0,0,0,NaN
37,2021-03-07,NY,1681169.0,NaN,NaN,NaN,totalTestEncountersViral,39695100.0,4789.0,NaN,...,NaN,59,0,8b1ad6376deb03844d4e5e3f615197da1b3a214e,0,0,0,0,0,NaN
38,2021-03-07,OH,978471.0,142113.0,NaN,NaN,totalTestsViral,10257157.0,820.0,50881.0,...,NaN,0,33,b32fec674723dd2c970e0f0c05036a44be63b80b,0,0,0,0,0,NaN
39,2021-03-07,OK,428997.0,NaN,3146300.0,2984.0,posNeg,3575297.0,346.0,24332.0,...,NaN,0,55,3019887dd90821b78021a57adfdafde0617d7a31,0,0,0,0,0,NaN
40,2021-03-07,OR,157079.0,NaN,NaN,NaN,totalTestsViral,3850973.0,158.0,8714.0,...,NaN,3,0,1ad86cf428e4cfe4db9d50dbee81e76f8a780e29,0,0,0,0,0,NaN
41,2021-03-07,PA,948643.0,134103.0,3942124.0,NaN,totalTestEncountersViral,10681716.0,1587.0,NaN,...,NaN,32,0,cc747d66ac5b93580b1cd7b3f292eb5ee0fb5910,0,0,0,0,0,NaN
42,2021-03-07,PR,101632.0,8012.0,305972.0,NaN,posNeg,407604.0,134.0,NaN,...,NaN,3,0,19eb8a58faff57a7aba79ef467260b8ccd35a873,0,0,0,0,0,NaN
43,2021-03-07,RI,128781.0,NaN,677570.0,NaN,totalTestEncountersViral,3123348.0,141.0,9020.0,...,NaN,0,0,604774c9b6670cbf0a7060307078cfd0e6504e4d,0,0,0,0,0,NaN
44,2021-03-07,SC,525865.0,75888.0,4657179.0,NaN,posNeg,5183044.0,579.0,20725.0,...,NaN,35,66,c5272b7792f489dd298d492dd7de3d822a4a6638,0,0,0,0,0,NaN
45,2021-03-07,SD,113589.0,12899.0,314540.0,NaN,totalTestsViral,701924.0,72.0,6705.0,...,NaN,2,13,b21c02251eddfda5478494054c1d8626d9c5079e,0,0,0,0,0,NaN
46,2021-03-07,TN,782206.0,128301.0,NaN,NaN,totalTestsViral,6872745.0,851.0,18870.0,...,NaN,0,0,8dbae9bf92c2cb76e0e4c5673175365e9d53e071,0,0,0,0,0,NaN
47,2021-03-07,TX,2686818.0,365961.0,NaN,NaN,totalTestsViral,19907384.0,4721.0,NaN,...,NaN,84,0,3fcdc4c2d3b36a167a791fa8677cf5d19ca67464,0,0,0,0,0,NaN
48,2021-03-07,UT,374850.0,NaN,1560293.0,NaN,totalTestsViral,2910121.0,212.0,14891.0,...,NaN,1,24,d759cc6bb12e652ba45ca3a0dbd31f3b951eae34,0,0,0,0,0,NaN
49,2021-03-07,VA,585700.0,124528.0,NaN,169.0,totalTestEncountersViral,6038209.0,1127.0,24661.0,...,NaN,77,24,58ad2cd3f6aa6b7a6c2f9582b0d521a559461f2a,0,0,0,0,0,NaN
50,2021-03-07,VI,2714.0,NaN,46167.0,80.0,posNeg,48881.0,NaN,NaN,...,NaN,0,0,af836e98493cc7b5474acf9302ffe87d9568a0db,0,0,0,0,0,NaN
51,2021-03-07,VT,16083.0,448.0,320060.0,NaN,totalTestsViral,1124215.0,31.0,NaN,...,NaN,0,0,ac73442d27f7fec957e7a11a9123f360b4a15724,0,0,0,0,0,NaN
52,2021-03-07,WA,344532.0,19479.0,NaN,NaN,totalTestEncountersViral,5393756.0,431.0,19599.0,...,NaN,0,43,d05df9ca1d090fd6a3f3f864eb442dc471e5861e,0,0,0,0,0,NaN
53,2021-03-07,WI,621654.0,54961.0,2647864.0,31.0,totalTestEncountersViral,7080595.0,249.0,26457.0,...,NaN,4,25,ea0056371780c0d00c44fa4f40092e7e0708a929,0,0,0,0,0,NaN
54,2021-03-07,WV,133445.0,26816.0,NaN,NaN,totalTestsViral,2236551.0,179.0,NaN,...,NaN,2,0,0884533b2e52491726d3fecba78a4971bfa7bc4d,0,0,0,0,0,NaN
55,2021-03-07,WY,54764.0,8367.0,182264.0,NaN,totalTestsViral,649293.0,21.0,1391.0,...,NaN,0,0,9cbc8bdcabbaf1f301ec1e48f8c23a4c65753282,0,0,0,0,0,NaN

In [49]:
# Step 2: Copy/paste previous cell's to this cell
# Chain to the previous code to sort values in descending order of deaths

# vvv Your code below vvv
recent_death_df = df[["date", "state", "death"]]
recent_death_df = recent_death_df.sort_values("death", ascending=False)

# ^^^ Your code above ^^^

# Show output of new dataframe
recent_death_df

          date state  death
5   2021-03-07    CA  54124
47  2021-03-07    TX  44451
37  2021-03-07    NY  39029
10  2021-03-07    FL  32266
41  2021-03-07    PA  24349
34  2021-03-07    NJ  23574
16  2021-03-07    IL  23014
11  2021-03-07    GA  17906
38  2021-03-07    OH  17656
24  2021-03-07    MI  16658
21  2021-03-07    MA  16417
4   2021-03-07    AZ  16328
17  2021-03-07    IN  12737
46  2021-03-07    TN  11543
30  2021-03-07    NC  11502
1   2021-03-07    AL  10148
20  2021-03-07    LA   9748
49  2021-03-07    VA   9596
44  2021-03-07    SC   8754
26  2021-03-07    MO   8161
22  2021-03-07    MD   7955
7   2021-03-07    CT   7704
53  2021-03-07    WI   7106
28  2021-03-07    MS   6808
25  2021-03-07    MN   6550
6   2021-03-07    CO   5989
14  2021-03-07    IA   5558
2   2021-03-07    AR   5319
52  2021-03-07    WA   5041
36  2021-03-07    NV   5037
19  2021-03-07    KY   4819
18  2021-03-07    KS   4812
39  2021-03-07    OK   4534
35  2021-03-07    NM   3808
43  2021-03-07    RI   2547
54  2021-03-07    WV   2325
40  2021-03-07    OR   2296
32  2021-03-07    NE   2113
42  2021-03-07    PR   2062
48  2021-03-07    UT   1976
45  2021-03-07    SD   1900
15  2021-03-07    ID   1879
31  2021-03-07    ND   1478
9   2021-03-07    DE   1473
29  2021-03-07    MT   1381
33  2021-03-07    NH   1184
8   2021-03-07    DC   1030
23  2021-03-07    ME    706
55  2021-03-07    WY    682
13  2021-03-07    HI    445
0   2021-03-07    AK    305
51  2021-03-07    VT    208
12  2021-03-07    GU    133
50  2021-03-07    VI     25
27  2021-03-07    MP      2
3   2021-03-07    AS      0

In [50]:
# Step 3: Create new dataframe named df_topdeaths
# Use iloc to show just the first 10 rows,
# We want this to become independent of the previous dataframe so use COPY. 
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.copy.html

# vvv Your code below vvv
df_topdeaths = recent_death_df.copy().iloc[:10]

# ^^^ Your code above ^^^
df_topdeaths

          date state  death
5   2021-03-07    CA  54124
47  2021-03-07    TX  44451
37  2021-03-07    NY  39029
10  2021-03-07    FL  32266
41  2021-03-07    PA  24349
34  2021-03-07    NJ  23574
16  2021-03-07    IL  23014
11  2021-03-07    GA  17906
38  2021-03-07    OH  17656
24  2021-03-07    MI  16658

In [52]:
# Step 4: Add ranks
# Add a column to the data frame called rank. Replace it with the decending rank of deaths.
# Most deaths would be rank of one. Use pandas rank function. One line of code.

# vvv Your code below vvv
df_topdeaths['rank'] = df_topdeaths['death'].rank(method="min", ascending=False)

# ^^^ Your code above ^^^

df_topdeaths

          date state  death  rank
5   2021-03-07    CA  54124   1.0
47  2021-03-07    TX  44451   2.0
37  2021-03-07    NY  39029   3.0
10  2021-03-07    FL  32266   4.0
41  2021-03-07    PA  24349   5.0
34  2021-03-07    NJ  23574   6.0
16  2021-03-07    IL  23014   7.0
11  2021-03-07    GA  17906   8.0
38  2021-03-07    OH  17656   9.0
24  2021-03-07    MI  16658  10.0

In [60]:
# Step 5: Use pandas' tolist function to create a list of the top ten states
#       Name the list topstates, it should only include 10 items

# vvv Your code below vvv
topstates = df_topdeaths["state"].tolist()
# ^^^ Your code above ^^^# Show output of new list
topstates

['CA', 'TX', 'NY', 'FL', 'PA', 'NJ', 'IL', 'GA', 'OH', 'MI']

In [65]:
# Step 6: Make a simple bar chart where the x-axis is state and the y-axis is total deaths
# Include a title that shows the date of the data (do not hard code it)
# That date should be the max date of the data frame
# Optional: set a data label at the top of each bar

# vvv Your code below vvv
topdeaths = df_topdeaths["death"].tolist()
df = pd.DataFrame({'States':topstates, 'Deaths':topdeaths})
title = f"States with Highest COVID-19 Related Deaths as of {df_topdeaths['date'].iloc[0]}"
df.plot.bar(x='States', y='Deaths', title=title, color=["green", "red", "blue"])
# ^^^ Your code above ^^^

SyntaxError: f-string: unmatched '[' (<ipython-input-65-75775b45c513>, line 9)

## Reminder:
*Before submitting:*
* Run all cells
* Save the file
* Be sure your last name is part of the file name